### ISSUE TITLE
Problem compiling driver

### ISSUE THREAD

**Issue by HeroofHell** [NMan1/Rainbow-Six-Cheat#1]
Hi, 
Since the OverflowR6.sln in the folder OverflowDriver doesn't contain anything I added all the files in the folder to the solution. But when I build a .sys is not generated even though I specified that in the project properties and the build has no errors. I would appreciate any help possible.

**Comment by NMan1** [comment]
> Hi,
> Since the OverflowR6.sln in the folder OverflowDriver doesn't contain anything I added all the files in the folder to the solution. But when I build a .sys is not generated even though I specified that in the project properties and the build has no errors. I would appreciate any help possible.

1. Right click on "OverflowR6.sln" in the first folder.
2. Open it in a text editor such as notepad++
3. Go to the 8th or so line where it says "OverflowDriver" with the path to the right. Change the directory path to the correct one on your system
4. Re-open or reload the solution in visual studio. 
5. Compile in x64 Debug - make sure you have the windows driver development kit downloaded and configured correctly.

**Comment by HeroofHell** [comment]
Thank you so much for your help, I really appreciate it. It now works :D
