### ISSUE TITLE
How to setup the database

### ISSUE THREAD

**Issue by Goalie31** [NMan1/Rainbow-Six-Cheat#12]
Hi, I was wondering on how to setup the database, it would be great if you could answer me through discord for more help and screen sharing, but if not here is fine too. Thank you!!!

Jk3171#7561

**Comment by NMan1** [comment]
I would recommend using Microsoft’s azure MySql database because you get a free trial and a bunch of credits which can be used for the cost of storage (for the db). So set that up 

Then once that’s done go to the Azure portal and find the database information, the name and password etc. Fill that information in this line:

https://github.com/NMan1/Rainbow-Six-Cheat/blob/7ce333b1392fd7df90413fa24e1e1bfab90e0aa3/Login.cpp#L453
https://github.com/NMan1/Rainbow-Six-Cheat/blob/7ce333b1392fd7df90413fa24e1e1bfab90e0aa3/Login.cpp#L454
https://github.com/NMan1/Rainbow-Six-Cheat/blob/7ce333b1392fd7df90413fa24e1e1bfab90e0aa3/Login.cpp#L455

Once that is all accurately filled out create a schema in the database (I like to use mysql workbench) either named “users”, since that’s what it is in the source, 
https://github.com/NMan1/Rainbow-Six-Cheat/blob/7ce333b1392fd7df90413fa24e1e1bfab90e0aa3/Login.cpp#L473
Or of course you can change it. Doesn’t matter along as they’re the same with the database. 

Next make a table inside of that schema and again make sure it’s the same in the source as to what you named it. In the source it’s customers. 

Finally for whatever you want to use the dB for I’m assuming obviously for logging in maybe a hwid check and license, as the source already has. You need to set up equivalent columns in the previous table for each thing you want to do/check.  

This line here,
https://github.com/NMan1/Rainbow-Six-Cheat/blob/7ce333b1392fd7df90413fa24e1e1bfab90e0aa3/Login.cpp#L484
Gets the string in the third column which is the username column. Use the numbers to set the columns up in order or they’ll be all mixed up. 

These sources will help a lot:
 https://docs.microsoft.com/en-us/azure/mysql/connect-cpp

https://youtu.be/RSHevYMwCVw

**Comment by Goalie31** [comment]
I will inform you on how this works! Thank you for such a quick response!!!
But may I ask, there is no bypass in this correct?

**Comment by NMan1** [comment]
No problem. Yes the cheat uses a kernel driver with shared memory which will bypass battle eye easily and will be safe as long as not a lot of people use it.

**Comment by Goalie31** [comment]
Is there a way of using without having Microsoft Azure? If so please
explain. Thank you so much for quick responses, it means a lot.

**Comment by NMan1** [comment]
Just remove the database code and put a hard coded password

**Comment by Goalie31** [comment]
We figured it out, thank you though!

**Comment by jk3171** [comment]
How do I remove the database code to add the hard coded password?

**Comment by Goalie31** [comment]
Is there a way to set it up with auth.gg?

**Comment by jk3171** [comment]
Can we remove whole login?

**Comment by NMan1** [comment]
idk what auth.gg is but probably. 

> Can we remove whole login?
Yes, obviously. Just delete the login function and the dependent functions to it. What kind of question is that

**Comment by jk3171** [comment]
Lmao, I suck at C++ and I don't know how to do that exactly

**Comment by NMan1** [comment]
1. highlight login 
2. press backspace
3. add if statement for your password

**Comment by jk3171** [comment]
On main.cpp?

**Comment by jk3171** [comment]
Is there a walkthrough you can give me, please?

**Comment by NMan1** [comment]
Id be glad to help you, if you showed effort

**Comment by jk3171** [comment]
I haven't done software dev in years and I only do web design now adays. I just need something like what you gave my friend Goalie. Plus, there are so many files here lol

**Comment by NMan1** [comment]
Ok? If you want to use this put effort in, im not santa for cheats. If you had an error relative to my code or compiling then sure Id assist you at will. But your problem is not being able to remove a function, which if you've even done ANY programming at all Id think you'd know how to simply do that.

**Comment by jk3171** [comment]
You just have so much going on in here, that it's getting confusing. but, I also can't compile it for some reason.

**Comment by NMan1** [comment]
Ok, fair enough. It is a very large project. For the login problem just set paste this at line 46 in main.cpp (this may or may not worked I haven't worked on this project in awhile.)

`
g_Settings::bDisplayLogin = true;
Auth::Authenitcation = true;
`

Then comment out this line https://github.com/NMan1/Rainbow-Six-Cheat/blob/0c674de9ba8860c8250d2224ea163539ec6a3944/Main.cpp#L42

For the compiling problem idk as you haven't shared any info on it.

**Comment by jk3171** [comment]
And I can just delete Login.cpp right?

**Comment by NMan1** [comment]
No dont delete it

**Comment by Goalie31** [comment]
Can I just say the amount of help you are giving is insane. And I would
also like to say that if you are free this would be much easier to be done
on discord. But of course this is not necessary. Thank you for helping us
out!

**Comment by jk3171** [comment]
Matt, we don't have to make it difficult for him; I am fine using Github

**Comment by Goalie31** [comment]
Ok, I apologize.

**Comment by jk3171** [comment]
I am having problems compiling :(

**Comment by NMan1** [comment]
What is the issue???? I cant help if I dont know the problem

**Comment by jk3171** [comment]
It doesn't give me the option in VS, and when I tried in CodeBlocks it is popping off all kinds of errors

**Comment by NMan1** [comment]
Did you read the readme compiling tutorial?

**Comment by jk3171** [comment]
I did not see that

**Comment by Goalie31** [comment]
Just back tracking to what JK said, we are experiencing some errors, code
errors.

**Comment by NMan1** [comment]
And what are they?

**Comment by Goalie31** [comment]
Code errors, JK what were the errors you were getting?

**Comment by Goalie31** [comment]
Apparently a lot of the code is not working..?

**Comment by jk3171** [comment]
Numerous errors about a lot of different stuff. If you open in VS and try to compile, it should pop up exactly what I saw

**Comment by jk3171** [comment]
issues with Authentication.h
Completely broken for some reason

**Comment by NMan1** [comment]
.... You guys seriously need to learn c++ before doing any of this. Your just wasting my time with stupid questions, a header file is broken??? It’s a header file???? It only has decelerations...

**Comment by Kennylovetheworld** [comment]
love this repo. Help a lot.

**Comment by Shao1409** [comment]
Hello. I'm having problems compiling this project (x64) what specific library do i have to download?

**Comment by NMan1** [comment]
Your going to need to be more specific than “I’m having problems”. What problems/errors?

**Comment by Shao1409** [comment]
Severity	Code	Description	Project	File	Line	Suppression State
Error (active)	E1696	cannot open source file "jdbc/cppconn/sqlstring.h"	OverflowR6	C:\Users\R6\Desktop\Rainbow-Six-Cheat-master\Authentication.h	3	
Error (active)	E1696	cannot open source file "jdbc/mysql_driver.h"	OverflowR6	C:\Users\R6\Desktop\Rainbow-Six-Cheat-master\Authentication.h	4	
Error (active)	E1696	cannot open source file "jdbc/mysql_connection.h"	OverflowR6	C:\Users\R6\Desktop\Rainbow-Six-Cheat-master\Authentication.h	5	
Error (active)	E1696	cannot open source file "jdbc/cppconn/driver.h"	OverflowR6	C:\Users\R6\Desktop\Rainbow-Six-Cheat-master\Authentication.h	6	
Error (active)	E1696	cannot open source file "jdbc/cppconn/exception.h"	OverflowR6	C:\Users\R6\Desktop\Rainbow-Six-Cheat-master\Authentication.h	7	
Error (active)	E1696	cannot open source file "jdbc/cppconn/prepared_statement.h"	OverflowR6	C:\Users\R6\Desktop\Rainbow-Six-Cheat-master\Authentication.h	8	
Error (active)	E0276	name followed by '::' must be a class or namespace name	OverflowR6	C:\Users\R6\Desktop\Rainbow-Six-Cheat-master\Authentication.h	18	
Error (active)	E0276	name followed by '::' must be a class or namespace name	OverflowR6	C:\Users\R6\Desktop\Rainbow-Six-Cheat-master\Authentication.h	18	
Error (active)	E0276	name followed by '::' must be a class or namespace name	OverflowR6	C:\Users\R6\Desktop\Rainbow-Six-Cheat-master\Authentication.h	18	
Error (active)	E0276	name followed by '::' must be a class or namespace name	OverflowR6	C:\Users\R6\Desktop\Rainbow-Six-Cheat-master\Authentication.h	18	
Error (active)	E0276	name followed by '::' must be a class or namespace name	OverflowR6	C:\Users\R6\Desktop\Rainbow-Six-Cheat-master\Login.cpp	410	
Error (active)	E0276	name followed by '::' must be a class or namespace name	OverflowR6	C:\Users\R6\Desktop\Rainbow-Six-Cheat-master\Login.cpp	410	
Error (active)	E0276	name followed by '::' must be a class or namespace name	OverflowR6	C:\Users\R6\Desktop\Rainbow-Six-Cheat-master\Login.cpp	410	
Error (active)	E0276	name followed by '::' must be a class or namespace name	OverflowR6	C:\Users\R6\Desktop\Rainbow-Six-Cheat-master\Login.cpp	410

**Comment by Shao1409** [comment]
Compiling issues

**Comment by Shao1409** [comment]
most likely becouse im missing a library

**Comment by robburito** [comment]
wait is this for ps4? or ?

**Comment by robburito** [comment]
Does anyone have hacks for ps4 r6

**Comment by Shao1409** [comment]
goddamn

**Comment by Shao1409** [comment]
how tf did u even find youre way here while being so dumb LMAO

**Comment by Shao1409** [comment]
OH SHOOT im missing the SQL lib, just got it with the visual studio installer :)

**Comment by Shao1409** [comment]
could u remove the sql and replace it with a password for us? it just doesnt work for me

**Comment by Shao1409** [comment]
Yo, i have decided to learn more c++, now that i understand ur code (XD) i decided to work with it.
i replaced the sql tools with a hard coded login. My problem: the gui never showes up. After Showin the console i got this error:

**Comment by Shao1409** [comment]
Assertion failed: GImGui != 0 && "No current context. Did you call ImGui::CreateContext() and ImGui::SetCurrentContext() ?", file C:\Users\Fixed\Desktop\ShellyPaste\imgui.cpp, line 3114

**Comment by Shao1409** [comment]
i have also just tried to instantly call the gui but with no success. im still new to this so i hope i dont sound like an idiot. XD
what i mean?:

int main();
{
                                Menu::BeginDraw();
				Menu::RenderMenu();
				Menu::EndDraw();
}

**Comment by NMan1** [comment]
That's not how ImGui, or for that matter any rendering library woks. ImGui has many issues on its repo with the similar error & solutions. Google it, and use Visual Studios debugger to see where the error is exactly thrown.

**Comment by Shao1409** [comment]
i mean wasnt this source working when u compiled it? Couse this error seems to occure by not defining the window size.

**Comment by NMan1** [comment]
Thats not why the error occurs. And the window size is defined.... https://github.com/NMan1/Rainbow-Six-Cheat/blob/74a04e2b89312a78395b5eb51fb4212744fc68a2/GUI.cpp#L218 I suggest you should go back to learning.

**Comment by Shao1409** [comment]
exactly. i don get why it doesnt work :(

**Comment by Shao1409** [comment]
why dont you replace it for us with a hard coded login sensei

**Comment by NMan1** [comment]
If you cannot do that yourself then you should not be making cheats. Like I said previously, go back to learning.

**Comment by Shao1409** [comment]
f u i did replace the pw, the gui just show up

**Comment by Shao1409** [comment]
if u would try to do it u would realise that

**Comment by NMan1** [comment]
Hmmm I wonder why the UI still shows? Maybe because your still fucking running the menu rendering loop? And calling the menu function? You are an idiot.  Please fuck off

**Comment by Shao1409** [comment]
idk why but whatever i try i get a force close XD

**Comment by Shao1409** [comment]
Assertion failed: GImGui != 0 && "No current context. Did you call ImGui::CreateContext() and ImGui::SetCurrentContext() ?", file C:..\imgui.cpp, line 3114
