### ISSUE TITLE
Installer.exe

### ISSUE THREAD

**Issue by 5DcOOKIE** [NMan1/Rainbow-Six-Cheat#16]
Hello! first of all beautiful written code. i went through most of it debugging my to run. i managed to bypass the login thing but now im getting this error in the console

**'Installer.exe' is not recognized as an internal or external command,
operable program or batch file.**

so basically its getting stuck in the while loop inside the loadDriver function

`if (!Driver.OpenFile())
		{
			int ret = system(xorstr_("Installer.exe"));
			LocateDriver();
		}`

any help would be appreciated. went through all the other issues raised on this post. i see you hate dumb people who cant code :p. trust me i am not that <3 Thanks!

**Comment by NMan1** [comment]
I don’t hate dumb people who can code, I dislike people who don’t try and want to be spoon fed. As for your issue, the error tells you tell answer. 

The code is trying to execute a command to launch “installer.exe”, and as the error says, you obviously don’t have that executable. And you shouldn’t as I didn’t include that. 

You need to remove that and manually load the driver however you chose, likely kdmapper. But note, make sure to keep the LocateDriver call as that insures it can successfully communicate with it.

**Comment by 5DcOOKIE** [comment]
Understood! i have tthe KDmapper set. can you point the the driver file which needs to be loaded? it is also not included in the repo i guess?

**Comment by NMan1** [comment]
You load the driver you build from the source code... that’s kind of the whole point of the project?

**Comment by 5DcOOKIE** [comment]
i am unable to compile the driver. a little procedure from you would be of great help. just basic steps. Thanks!

**Comment by NMan1** [comment]
Why what’s the issue your having?

**Comment by 5DcOOKIE** [comment]
i am a student not even graduated yet. iv never compiled a drivere before but im a quick learner. i have the sdk and the wdk installed now. how do i compile the driver?

**Comment by NMan1** [comment]
You click build on the project in your ide? Unless your having another issue which has a specific error it’s hard to diagnose the issue if you haven’t told me the problem. If you don’t know how to compile a driver you shouldn’t even be using this, sorry.
