### ISSUE TITLE
Unhandled exception at 0x00007FF79A3B2B4D in OverflowR6.exe

### ISSUE THREAD

**Issue by awfulpotato** [NMan1/Rainbow-Six-Cheat#19]
The output says:
'OverflowR6.exe' (Win32): Loaded 'C:\Windows\System32\oleacc.dll'. 
Unhandled exception at 0x00007FF79A3B2B4D in OverflowR6.exe: Fatal program exit requested.

apparently the error is coming from here: (line 77 abort.c)

```
if (__abort_behavior & _CALL_REPORTFAULT)
    {
        #if defined _M_ARM || defined _M_ARM64 || defined _UCRT_ENCLAVE_BUILD
        __fastfail(FAST_FAIL_FATAL_APP_EXIT);
        #else
        if (IsProcessorFeaturePresent(PF_FASTFAIL_AVAILABLE))
            __fastfail(FAST_FAIL_FATAL_APP_EXIT);

        __acrt_call_reportfault(_CRT_DEBUGGER_ABORT, STATUS_FATAL_APP_EXIT, EXCEPTION_NONCONTINUABLE);
        #endif
    }
```

I've looked the number up and nothing showed up, I have all libraries linked to the project, I've tried to dig more into to find the problem and it's coming from a file "abort.cpp" I tried to find it out myself, looked on forums, but I just cant figure it out. why cant I compile it properly.

btw, code optimization is off, Debug x64.

**Comment by NMan1** [comment]
Step through the code and see where the exception gets thrown

**Comment by awfulpotato** [comment]
> Step through the code and see where the exception gets thrown

GUI line 167 (on void menu init)
any idea why?

**Comment by NMan1** [comment]
What piece of code exactly

**Comment by awfulpotato** [comment]
`void Menu::Init()
{
	/* Colors */
	StyleColorsBlueMain();
	SetColorEditOptions(ImGuiColorEditFlags_HEX);

	/* Setup Style */
	ImGuiStyle& style = GetStyle();
	Status = " Rainbow Six Seige";

	style.Alpha = 1.f;
	style.WindowPadding = ImVec2(8, 8);
	style.WindowMinSize = ImVec2(32, 32);
	style.WindowRounding = 0.0f; //4.0 for slight curve
	style.WindowTitleAlign = ImVec2(0.5f, 1.5f);
	style.ChildRounding = 0.0f;
	style.FramePadding = ImVec2(4, 3);
	style.FrameRounding = 0.0f; //2.0
	style.ItemSpacing = ImVec2(8, 4);
	style.ItemInnerSpacing = ImVec2(4, 4);
	style.TouchExtraPadding = ImVec2(0, 0);
	style.IndentSpacing = 21.0f;
	style.ColumnsMinSpacing = 3.0f;
	style.ScrollbarSize = 6.0f;
	style.ScrollbarRounding = 16.0f; //16.0
	style.GrabMinSize = 0.1f;
	style.GrabRounding = 16.0f; //16.0
	style.ButtonTextAlign = ImVec2(0.5f, 0.5f);
	style.DisplayWindowPadding = ImVec2(22, 22);
	style.DisplaySafeAreaPadding = ImVec2(4, 4);
	style.AntiAliasedLines = true;
	style.CurveTessellationTol = 1.25f;

	ImGuiIO& io = GetIO();
	io.IniFilename = nullptr;
	io.LogFilename = nullptr;

	TCHAR szPath[MAX_PATH];
	SHGetFolderPath(NULL, CSIDL_FONTS, NULL, NULL, szPath);

	std::string Path = szPath;
	std::string pTahoma{ Path + "\\Tahoma.ttf" };
	//std::string pRuda{ Path + "\\Ruda-Bold.ttf" };

	Font16 = io.Fonts->AddFontFromFileTTF(pTahoma.c_str(), 16.0f);
	Font12 = io.Fonts->AddFontFromFileTTF(pTahoma.c_str(), 12.0f);
	Font14 = io.Fonts->AddFontFromFileTTF(pTahoma.c_str(), 14.0f);
	Font18 = io.Fonts->AddFontFromFileTTF(pTahoma.c_str(), 18.0f);
	Font24 = io.Fonts->AddFontFromFileTTF(pTahoma.c_str(), 24.0f);

	int my_image_width = 370;
	int my_image_height = 90;
	bool ret = LoadTextureFromFile(Menu::Logo, &LogoTexture, &my_image_width, &my_image_height);
	IM_ASSERT(ret);

	return;
}`

debugger pops up saying "abort has been called"

**Comment by NMan1** [comment]
> What piece of code exactly

What line of code??....

**Comment by awfulpotato** [comment]
bool ret = LoadTextureFromFile(Menu::Logo, &LogoTexture, &my_image_width, &my_image_height); <-- this one, triggers abort()

**Comment by NMan1** [comment]
Think about what that line of code is trying to do. Its trying to load a texture from a path, you obviously dont have that texture therefor it crashes...

**Comment by awfulpotato** [comment]
I know that, but that line doesnt specify what texture or where, it just says its trying to load, what isn't helpful been cracking my head over this for hours, but I cant figure it out what texture, I've read your post million times trying to spot something
but I found nothing....

anyways thank you for replying, sorry to take your time.

**Comment by NMan1** [comment]
Yes it does specify what and where. It’s literally in the parameters and arguments passed. 
https://github.com/NMan1/Rainbow-Six-Cheat/blob/7c321921fe03f9ef3a49180aa7a67501f8290bfa/GUI.cpp#L68
“File name”

Along with if you looked at the first argument being passed in Menu::Logo, you’d see (although it’s commented my point still remains)
https://github.com/NMan1/Rainbow-Six-Cheat/blob/a0cb718624d7880ede95f4a252345dae9e816fc7/GUI.cpp#L21

That is obviously a path to a image/texture that I previously used but didn’t include. Why don’t you just comment out the line I don’t even think it’s used (could be wrong this was an old project I don’t remember). Although I’m going to assume you don’t know c++ and in that case don’t bother with this project, you won’t be able to get it up and running.

**Comment by awfulpotato** [comment]
thank you, i actually had missed the comment, but thx anyways :)

**Comment by NMan1** [comment]
No problem

**Comment by awfulpotato** [comment]
But you wer right, i dont know much c++, but I don't live on a rich country and a make almost no money, so I cannot afford spending 90 bux a month a cheat for r6, so I will try my ways till I get one! 

Peace, have a nice day mate

**Comment by NMan1** [comment]
Well here’s my opinion, it’s much much much better to learn how to program than to waste 90 bucks a month on cheats for a damn video game. Buying cheats is sad, spending that much money just for an advantage in a video game is extremely sad. It’s unfortunate people get addicted to it. Never waste your money on that shit. Instead buy programming books or something that’ll benefit you useful knowledge. 

Anyways, good luck and keep learning!

**Comment by awfulpotato** [comment]
dude, so i got over the error, i compile it a windows shows up and closes immediately, on task manager I can the program running, so what's next step?

**Comment by NMan1** [comment]
Listen man, I’m not trying to be an asshole but it’s in your best interest to learn what the fuck your doing before attempting to cheat in a game with one of the best anti cheats. Your going to go no where without the right knowledge. Im not going to sit here and waste my time guiding and spoon feeding you to a ban.

**Comment by awfulpotato** [comment]
yeah i give up, thx tho
