### ISSUE TITLE
mysqlclient.lib doesn't exist / Crash without

### ISSUE THREAD

**Issue by HeroofHell** [NMan1/Rainbow-Six-Cheat#2]
Hi,
Thank you so much for helping me with my previous question. I've gone ahead and successfully built the Driver. When building the usermode however I ran into the problem that I don't have mysqlclient.lib in my mysql connector cpp folder, and if I remove it the program directly crashes although I have made a MYSQL database with table and I changed the server, username and password in Auth::Login() corresponding to that. I would again greatly appreciate your help.

P.S I tried adding you on discord since your discord is still in the source but I can't find you.

**Comment by NMan1** [comment]
Make sure you are linking against the mysql library. 

Also you need the mysql dll dependencies in the directory where you run the OverflowR6.exe

It’s hard to say what’s going wrong if you didn’t provide much information at all. Just debug it yourself, it’s not that hard. Also if your trying to start a pay to cheat with this source everyone will be banned in the first few days Lel.

**Comment by HeroofHell** [comment]
lol no I don't want to start a paid cheat but I would like to use it myself. I do have the mysql dll dependencies in the directory. Thanks for the help anyways :D

**Comment by HeroofHell** [comment]
Ok yeah nevermind I found it I was just being stupid as shit

**Comment by qqwtt** [comment]
@HeroofHell could you share the solution? I'm stuck with the same problem(instant crash)

**Comment by NMan1** [comment]
> @HeroofHell could you share the solution? I'm stuck with the same problem(instant crash)

When encountering bugs whilst programming your best friend is visual studios amazon debugging tools. Just set breakpoints throughout the entry point and see where it crashes.

**Comment by qqwtt** [comment]
> When encountering bugs whilst programming your best friend is visual studios amazing debugging tools. Just set breakpoints throughout the entry point and see where it crashes.
I actually succeded launching the launcher and after pressing inject nothing happened xdxd
I loaded the driver with kdmapper idk if im doing something wrong

**Comment by NMan1** [comment]
> When encountering bugs whilst programming your best friend is visual studios amazing debugging tools. Just set breakpoints throughout the entry point and see where it crashes.
> I actually succeded launching the launcher and after pressing inject nothing happened xdxd
> I loaded the driver with kdmapper idk if im doing something wrong

Look at the driver output with dbgview. Also could be outdated offsets as well. Generally what happens is you click inject and it should load the driver itself if you move kidnapper into the same directory and rename is as “Installer” (look at the code)

Then when the game loads the menu will open, unless the offsets aren’t updated then it won’t load

**Comment by HeroofHell** [comment]
@qqwtt do you have discord?
