### ISSUE TITLE
When click inject it say incorrect usage

### ISSUE THREAD

**Issue by JayneFrack** [NMan1/Rainbow-Six-Cheat#5]
pls i asked question but you not answer when click inject it say incorrect usage in console and when i try map driver my pc crash. for which windows version is driver and

**Comment by NMan1** [comment]
Why do you keep opening new issues? Every question you have this is what I read “I have no idea what I’m doing please fix everything for me”

**Comment by JayneFrack** [comment]
pls last question what windows version i need?
